FROM docker.io/library/debian:13-slim

ARG DEBIAN_FRONTEND=noninteractive

ENV LANG=C.UTF-8 \
    LC_ALL=C.UTF-8 \
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    CARGO_HOME=/home/developer/.cargo \
    RUSTUP_HOME=/home/developer/.rustup

RUN dpkg --add-architecture i386 \
    && apt-get update \
    && apt-get install --yes --no-install-recommends \
        autoconf \
        automake \
        bash-completion \
        bc \
        binutils \
        binutils-aarch64-linux-gnu \
        binutils-riscv64-linux-gnu \
        bison \
        build-essential \
        ca-certificates \
        clang \
        clang-format \
        clang-tidy \
        cmake \
        cpio \
        curl \
        dosfstools \
        file \
        flex \
        g++-multilib \
        gcc-multilib \
        gdb \
        git \
        golang-go \
        grub-common \
        grub-efi-amd64-bin \
        grub-pc-bin \
        iproute2 \
        iputils-ping \
        jq \
        less \
        libtool \
        lld \
        lldb \
        ltrace \
        make \
        meson \
        mtools \
        nasm \
        netcat-openbsd \
        ninja-build \
        nodejs \
        npm \
        openjdk-21-jdk-headless \
        ovmf \
        pkg-config \
        python3 \
        python3-dev \
        python3-pip \
        python3-venv \
        qemu-system-arm \
        qemu-system-misc \
        qemu-system-x86 \
        qemu-user \
        qemu-user-static \
        qemu-utils \
        ripgrep \
        rustc \
        cargo \
        seabios \
        shellcheck \
        socat \
        strace \
        sudo \
        tmux \
        unzip \
        valgrind \
        vim \
        wget \
        xauth \
        xorriso \
        xxd \
        xz-utils \
        yasm \
        zip \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update \
    && apt-get install --yes --no-install-recommends \
        bats \
        bear \
        binwalk \
        bsdextrautils \
        bvi \
        ccache \
        cppcheck \
        dhex \
        elfutils \
        entr \
        fd-find \
        gdb-multiarch \
        hexedit \
        lcov \
        patchelf \
        pv \
        rsync \
        srecord \
        tree \
        zstd \
    && rm -rf /var/lib/apt/lists/*

RUN groupadd --gid 1000 developer \
    && useradd --uid 1000 --gid 1000 --create-home --shell /bin/bash developer

COPY developer.sudoers /etc/sudoers.d/developer
RUN chmod 0440 /etc/sudoers.d/developer

USER developer
WORKDIR /workspace

CMD ["sleep", "infinity"]
